# Generated by Django 5.0 on 2023-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Add dependencies here if any, e.g., ('app_name', 'previous_migration')
    ]

    operations = [
    ]
