# Generated by Django 5.0 on 2023-12-05 07:12

from django.db import migrations
from django.contrib.auth.models import User
from django.db.utils import IntegrityError

def create_default_user(apps, schema_editor):
    try:
        if not User.objects.filter(username='default').exists():
            User.objects.create_user('default', password='defaultpassword')
    except IntegrityError:
        pass  # Default user already exists

class Migration(migrations.Migration):

    dependencies = [
        # Add dependencies here if any, e.g., ('app_name', 'previous_migration')
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
