# Generated by Django 5.0 on 2023-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('proves', 'Proves'), ('disproves', 'Disproves'), ('is_premise_of', 'Is Premise Of')], default='proves', max_length=20),
            preserve_default=False,
        ),
    ]
